name: portfolio_luizhbfilho
description: My portfolio in Flutter web.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  unicons: any
  google_fonts: ^2.1.0
  flutter_svg: ^1.1.1+1
  animated_text_kit: ^4.2.1
  url_launcher: ^5.5.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/my_photo.png
    - assets/images/space_background.gif
  uses-material-design: true
